# add the following to _config.yml file
title: MS Hossain
logo: profile.png
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
social:
  - network: ResearGate
    url: https://www.researchgate.net/profile/Md-Saddam-Hossain-16
#links: https://www.researchgate.net/profile/Md-Saddam-Hossain-16
#gem "github-pages", group: :jekyll_plugins
