# add the following to _config.yml file
title: MS Hossain
logo: profile.png
theme: jekyll-theme-minimal
links: https://www.researchgate.net/profile/Md-Saddam-Hossain-16
#gem "github-pages", group: :jekyll_plugins
